server:
  port: 8080

spring:
  application:
    name: discord
  profiles:
    active: token
  config:
    import: "optional:configserver:http://localhost:8081"
  cloud:
    config:
      name: discord
      profile: token

management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: key-brian